<h1><?php _e('Finished!', 'Install'); ?></h1>

<?php if ($showInfo) { ?>
    <p class="alert alert-info"><?php _e('If you wish to repeat the installation, please clear the configuration file "config.php".', 'Install'); ?></p>
<?php } ?>

<?php if ($autoGeneratedPassword) { ?>
    <p class="alert alert-success"><?php _e('Your password is:', 'Install'); ?> <strong><?php echo $autoGeneratedPassword; ?></strong></p>
<?php } ?>

<p class="text-center">
    <?php _e('ImpressPages has been successfully installed.', 'Install'); ?>
</p>
<p class="text-center">
    <a href="https://twitter.com/intent/tweet?button_hashtag=ImpressPages&text=Lucky%20me.%20I've%20just%20installed%20%23ImpressPages" class="twitter-hashtag-button" data-size="large" data-related="ImpressPages" data-url="http://www.impresspages.org" data-dnt="true">Tweet #ImpressPages</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    <br>
    <span class="fb-share-button" data-href="http://www.impresspages.org" data-type="button"></span>
</p>
<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/lt_LT/sdk.js#xfbml=1&appId=151985828271895&version=v2.0";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<p class="text-right"><a href="../admin" class="btn btn-primary btn-lg"><?php _e('Log in to your website', 'Install'); ?></a></p>
