<div class="ip">
    <div class="ipsModuleAdminIsAutogeneratedModal modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"><?php _e('Important Account Information', 'Ip-admin'); ?></h4>
                </div>
                <div class="modal-body">
                    <p><?php _e('Your user credentials were automatically generated.', 'Ip-admin'); ?></p>
                    <p><?php _e('You were automatically logged in with the following details.', 'Ip-admin'); ?></p>
                    <p class="alert alert-info">
                        <?php _e('URL to log in', 'Ip-admin'); ?>: <a href="<?php echo ipFileUrl('admin'); ?>"><?php echo ipFileUrl('admin'); ?></a><br>
                        <?php _e('Administrator username', 'Ip-admin'); ?>: <strong><?php echo $adminUsername; ?></strong><br>
                        <?php _e('Administrator password', 'Ip-admin'); ?>: <strong><?php echo $adminPassword; ?></strong><br>
                        <?php _e('Administrator email', 'Ip-admin'); ?>: <strong><?php echo $adminEmail; ?></strong><br>
                        <a href="#" type="button" class="ipsChange"><?php _e('Change credentials', 'Ip-admin'); ?></a>
                    </p>
                    <iframe style="width:0;height:0;border:none;" border="0" src="http://www.impresspages.org/installationscript2/?step=last"></iframe>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary ipsConfirm"><?php _e('Yes, I understand how to log in next time', 'Ip-admin'); ?></button>
                </div>
            </div>
        </div>
    </div>
</div>
