<?php
/**
 * @package ImpressPages

 *
 */
namespace Ip\Module\Design;


class System{


    public function init()
    {
        $dispatcher = \Ip\ServiceLocator::getDispatcher();

        $dispatcher->bind('site.clearCache', array($this, 'clearCacheEvent'));

        $configModel = ConfigModel::instance();
        if ($configModel->isInPreviewState()) {
            $this->initConfig();
        }

        $lessCompiler = LessCompiler::instance();
        if (\Ip\Config::isDevelopmentEnvironment()) {
            if ($lessCompiler->shouldRebuild(\Ip\Config::theme())) {
                $lessCompiler->rebuild(\Ip\Config::theme());
            }
        }

        $dispatcher->bind('site.beforeError404', array($this, 'catchError404'));



    }


    public function catchError404(\Ip\Event $event)
    {
        // we use parse_url() in order to support multiple domains and http, https protocols
        if (parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) == parse_url(\Ip\Config::themeUrl('ipAutogeneratedCss.css'), PHP_URL_PATH)) {
            $event->addProcessed();
        }
    }


    protected function initConfig()
    {
        $site = \Ip\ServiceLocator::getSite();
        ipAddJavascript(\Ip\Config::libraryUrl('js/jquery-ui/jquery-ui.js'));
        ipAddCss(\Ip\Config::libraryUrl('css/bootstrap/bootstrap.css'));
        ipAddJavascript(\Ip\Config::libraryUrl('css/bootstrap/bootstrap.js'));
        ipAddCss(\Ip\Config::libraryUrl('fonts/font-awesome/font-awesome.css'));
        ipAddJavascript(\Ip\Config::coreModuleUrl('Design/public/optionsBox.js'));
        ipAddJavascriptVariable('ipModuleDesignConfiguration', $this->getConfigurationBoxHtml());
        ipAddCss(\Ip\Config::coreModuleUrl('Design/public/optionsBox.css'));
        if (file_exists(\Ip\Config::themeFile(Model::INSTALL_DIR.'Options.js'))) {
            ipAddJavascript(\Ip\Config::themeUrl(Model::INSTALL_DIR . 'Options.js'));
        } elseif (file_exists(\Ip\Config::themeFile(Model::INSTALL_DIR.'options.js'))) {
            ipAddJavascript(\Ip\Config::themeUrl(Model::INSTALL_DIR . 'options.js'));
        }

        $model = Model::instance();
        $theme = $model->getTheme(\Ip\Config::theme());
        if (!$theme) {
            throw new \Ip\CoreException("Theme doesn't exist");
        }

        $options = $theme->getOptionsAsArray();

        $fieldNames = array();
        foreach($options as $option) {
            if (empty($option['name'])) {
                continue;
            }
            $fieldNames[] = $option['name'];
        }
        ipAddJavascriptVariable('ipModuleDesignOptionNames', $fieldNames);
    }

    protected function getConfigurationBoxHtml()
    {
        $configModel = ConfigModel::instance();

        $form = $configModel->getThemeConfigForm(\Ip\Config::theme());
        $form->removeClass('ipModuleForm');
        $variables = array(
            'form' => $form
        );
        $optionsBox = \Ip\View::create('view/optionsBox.php', $variables);
        return $optionsBox->render();
    }

    public function clearCacheEvent(\Ip\Event\ClearCache $e)
    {
        $lessCompiler = LessCompiler::instance();
        $lessCompiler->rebuild(\Ip\Config::theme());
    }

}


