<?php
/**
 * @package ImpressPages

 *
 */
namespace Ip\Internal\Design;


class System{


    public function init()
    {
        ipDispatcher()->addEventListener('site.clearCache', array($this, 'clearCacheEvent'));

        $configModel = ConfigModel::instance();
        if ($configModel->isInPreviewState()) {
            $this->initConfig();
        }

        $lessCompiler = LessCompiler::instance();
        if (ipConfig()->isDevelopmentEnvironment()) {
            if ($lessCompiler->shouldRebuild(ipConfig()->theme())) {
                $lessCompiler->rebuild(ipConfig()->theme());
            }
        }

        // TODOXX remove #131
        ipDispatcher()->addFilterListener('site.beforeError404', array($this, 'catchError404'));
    }


    public function catchError404($info)
    {
        // we use parse_url() in order to support multiple domains and http, https protocols
        if (parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) == parse_url(ipThemeUrl('ipAutogeneratedCss.css'), PHP_URL_PATH)) {
            // TODOXX make it some other way #131
            return false;
        }
    }


    protected function initConfig()
    {
        ipAddJs(ipFileUrl('Ip/Internal/Ip/assets/js/jquery-ui/jquery-ui.js'));
        ipAddCss(ipFileUrl('Ip/Internal/Ip/assets/bootstrap/bootstrap.css'));
        ipAddJs(ipFileUrl('Ip/Internal/Ip/assets/bootstrap/bootstrap.js'));
        ipAddCss(ipFileUrl('Ip/Internal/Ip/assets/fonts/font-awesome/font-awesome.css'));
        ipAddJs(ipFileUrl('Ip/Internal/Design/assets/optionsBox.js'));
        ipAddJsVariable('ipModuleDesignConfiguration', $this->getConfigurationBoxHtml());
        ipAddCss(ipFileUrl('Ip/Internal/Design/assets/optionsBox.css'));
        if (file_exists(ipThemeFile(Model::INSTALL_DIR.'Options.js'))) {
            ipAddJs(ipThemeUrl(Model::INSTALL_DIR . 'Options.js'));
        } elseif (file_exists(ipThemeFile(Model::INSTALL_DIR.'options.js'))) {
            ipAddJs(ipThemeUrl(Model::INSTALL_DIR . 'options.js'));
        }

        $model = Model::instance();
        $theme = $model->getTheme(ipConfig()->theme());
        if (!$theme) {
            throw new \Ip\Exception("Theme doesn't exist");
        }

        $options = $theme->getOptionsAsArray();

        $fieldNames = array();
        foreach($options as $option) {
            if (empty($option['name'])) {
                continue;
            }
            $fieldNames[] = $option['name'];
        }
        ipAddJsVariable('ipModuleDesignOptionNames', $fieldNames);
    }

    protected function getConfigurationBoxHtml()
    {
        $configModel = ConfigModel::instance();

        $form = $configModel->getThemeConfigForm(ipConfig()->theme());
        $form->removeClass('ipModuleForm');
        $variables = array(
            'form' => $form
        );
        $optionsBox = ipView('view/optionsBox.php', $variables);
        return $optionsBox->render();
    }

    public function clearCacheEvent($info)
    {
        $lessCompiler = LessCompiler::instance();
        $lessCompiler->rebuild(ipConfig()->theme());
    }

}
